backend:
  name: github
  repo: rearwing-endplate/paundoburijji
  branch: main

media_folder: assets
public_folder: /assets

collections:
  - name: dispatches
    label: Research Dispatches
    folder: dispatches
    create: true
    format: frontmatter
    extension: md
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Category, name: category, widget: select, options: ["salisminster", "burj"] }
      - { label: Publication Date, name: date, widget: datetime }
      - { label: Body Content, name: body, widget: markdown }
