media:
  input: assets
  output: /assets

content:
  - name: dispatches
    label: Research Dispatches
    type: collection
    path: dispatches
    fields:
      - name: title
        label: Title
        type: string
      - name: category
        label: Category
        type: select
        options:
          values: [salisminster, burj]
      - name: date
        label: Publication Date
        type: date
        options:
          time: true
      - name: body
        label: Body Content
        type: rich-text
